"""Agrego columnas en tabla productos

Revision ID: 05dd93c35d56
Revises: cd1cf773e90c
Create Date: 2025-07-23 17:50:16.537174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05dd93c35d56'
down_revision: Union[str, Sequence[str], None] = 'cd1cf773e90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('descuento', sa.String(), nullable=True))
    op.add_column('productos', sa.Column('precio_anterior', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('link_prod', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'link_prod')
    op.drop_column('productos', 'precio_anterior')
    op.drop_column('productos', 'descuento')
    # ### end Alembic commands ###
