"""Cambio en los modelos

Revision ID: 24f360dd18a2
Revises: 3cd3fc204187
Create Date: 2025-07-26 18:31:54.991370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f360dd18a2'
down_revision: Union[str, Sequence[str], None] = '3cd3fc204187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precios', sa.Column('descuento', sa.String(), nullable=True))
    op.add_column('precios', sa.Column('precio_anterior', sa.Float(), nullable=True))
    op.add_column('precios', sa.Column('link_producto', sa.Text(), nullable=True))
    op.drop_column('productos', 'precio_anterior')
    op.drop_column('productos', 'descuento')
    op.drop_column('productos', 'link_producto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('link_producto', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('descuento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('precio_anterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('precios', 'link_producto')
    op.drop_column('precios', 'precio_anterior')
    op.drop_column('precios', 'descuento')
    # ### end Alembic commands ###
