"""Cambio de campo a link_producto

Revision ID: 3cd3fc204187
Revises: 05dd93c35d56
Create Date: 2025-07-23 18:23:37.090488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd3fc204187'
down_revision: Union[str, Sequence[str], None] = '05dd93c35d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('link_producto', sa.Text(), nullable=True))
    op.drop_column('productos', 'link_prod')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('link_prod', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('productos', 'link_producto')
    # ### end Alembic commands ###
