"""Primeras tablas

Revision ID: cd1cf773e90c
Revises: 
Create Date: 2025-07-22 17:46:52.768172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1cf773e90c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=True)
    op.create_table('supermercados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supermercados_nombre'), 'supermercados', ['nombre'], unique=True)
    op.create_table('precios',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('super_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fecha_act', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['super_id'], ['supermercados.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'super_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precios')
    op.drop_index(op.f('ix_supermercados_nombre'), table_name='supermercados')
    op.drop_table('supermercados')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
